version: '3.9'

services:
  postgrest:
    image: postgrest/postgrest
    ports:
      - "3000:3000"
    environment:
      PGRST_DB_URI: postgres://postgres:Kyquan!2152155@host.docker.internal:5434/dental_website
      PGRST_DB_ANON_ROLE: web_anon
      PGRST_DB_SCHEMA: public
